In [ ]:
import pandas as pd
production=pd.Series([30,60,45,25],index=["wheat","rice","maize","barley"])
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
print(production["rice"])
print(production.loc["wheat"])
print(production.iloc[0])

60
30
30

In [ ]:
print(production.sum())
print(production.mean())
print(production.max())
print(production.idxmax())

160
40.0
60
rice

increased_production=production*1.10
print(increased_production)

In [ ]:
high_production=production[production>40]
print(high_production)
print()
print(production>40)

rice     60
maize    45
dtype: int64

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["alice","bob","charlie"],
    "age":[25,30,35],
    "city":["New York","Paris","Seoul"]
},index=["a","b","c"])
print(df)
print()
print(df.loc["b"])

      name  age      city
a    alice   25  New York
b      bob   30     Paris
c  charlie   35     Seoul

name      bob
age        30
city    Paris
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[["a","c"],["name","city"]])

      name  age      city
a    alice   25  New York
b      bob   30     Paris
c  charlie   35     Seoul

      name      city
a    alice  New York
c  charlie     Seoul

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["alice","bob","charlie"],
    "age":[25,30,35],
    "city":["New York","Paris","Seoul"]
},index=["a","b","c"])
print(df)
print()
print(df.loc["b"])
print(df.loc[df["age"]>28,["name","age"]])

      name  age      city
a    alice   25  New York
b      bob   30     Paris
c  charlie   35     Seoul

name      bob
age        30
city    Paris
Name: b, dtype: object
      name  age
b      bob   30
c  charlie   35

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["alice","bob","charlie"],
    "age":[25,30,35],
    "city":["New York","Paris","Seoul"]
},index=["a","b","c"])
print(df)
print(df.iloc[[0,2]])

      name  age      city
a    alice   25  New York
b      bob   30     Paris
c  charlie   35     Seoul
      name  age      city
a    alice   25  New York
c  charlie   35     Seoul

In [ ]:
import pandas as pd
data={
    "farm":["farm A","farm B","farm C","farm D"],
    "crop":["wheat","rice","wheat","maize"],
    "area_ha":[10,15,8,12],
    "production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

     farm   crop  area_ha  production_tons
0  farm A  wheat       10               30
1  farm B   rice       15               60
2  farm C  wheat        8               24
3  farm D  maize       12               36

In [ ]:
df.head(2)

     farm   crop  area_ha  production_tons
0  farm A  wheat       10               30
1  farm B   rice       15               60

In [ ]:
df.tail(2    )

     farm   crop  area_ha  production_tons
2  farm C  wheat        8               24
3  farm D  maize       12               36

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   farm             4 non-null      object
 1   crop             4 non-null      object
 2   area_ha          4 non-null      int64
 3   production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()

         area_ha  production_tons
count   4.000000         4.000000
mean   11.250000        37.500000
std     2.986079        15.779734
min     8.000000        24.000000
25%     9.500000        28.500000
50%    11.000000        33.000000
75%    12.750000        42.000000
max    15.000000        60.000000

In [ ]:
df["yield_ton_per_ha"]=df["production_tons"]/df["area_ha"]
print(df)

     farm   crop  area_ha  production_tons  yield_ton_per_ha
0  farm A  wheat       10               30               3.0
1  farm B   rice       15               60               4.0
2  farm C  wheat        8               24               3.0
3  farm D  maize       12               36               3.0

In [ ]:
print(df.iloc[[1,3]])

     farm   crop  area_ha  production_tons  yield_ton_per_ha
1  farm B   rice       15               60               4.0
3  farm D  maize       12               36               3.0

In [ ]:
df.iloc[[1,3],[0,1,2]]

     farm   crop  area_ha
1  farm B   rice       15
3  farm D  maize       12

In [ ]:
df.loc[[1,3],["farm","crop","area_ha"]]

     farm   crop  area_ha
1  farm B   rice       15
3  farm D  maize       12

In [ ]:
print(df["crop"]=="wheat")
print()
wheat_farms=df[df["crop"]=="wheat"]
print(wheat_farms)

0     True
1    False
2     True
3    False
Name: crop, dtype: bool

     farm   crop  area_ha  production_tons  yield_ton_per_ha
0  farm A  wheat       10               30               3.0
2  farm C  wheat        8               24               3.0

In [ ]:
high_yield=df[df["yield_ton_per_ha"]>3]
print(high_yield)

     farm  crop  area_ha  production_tons  yield_ton_per_ha
1  farm B  rice       15               60               4.0

In [ ]:
sorted_df=df.sort_values(by="production_tons",ascending=False)
print(sorted_df)

     farm   crop  area_ha  production_tons  yield_ton_per_ha
1  farm B   rice       15               60               4.0
3  farm D  maize       12               36               3.0
0  farm A  wheat       10               30               3.0
2  farm C  wheat        8               24               3.0

In [ ]:
avg_yield=df.groupby("crop")["yield_ton_per_ha"].sum()
print(avg_yield)

crop
maize    3.0
rice     4.0
wheat    6.0
Name: yield_ton_per_ha, dtype: float64